exclude: "poetry.lock"

repos:
  # Base pre-commit hook for simple checks & fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-ast # Check whether the files parse as valid Python
      - id: check-docstring-first # Checks a common error of defining a docstring after code
      - id: check-json # Check JSON files for parseable syntax
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-toml # Checks TOML files for parseable syntax
      - id: check-yaml # Check YAML files for parseable syntax
      - id: debug-statements # Check for debugger imports and `breakpoint()` calls in python
      - id: detect-private-key # Detect the presence of private keys
      - id: end-of-file-fixer # Ensures that files end with a newline
      - id: name-tests-test # Verifies that test files are named correctly
      - id: trailing-whitespace # Trims trailing whitespace

  # Black is an opinionated Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--config", "pyproject.toml"]

  # Ruff is a very fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # Mypy is a Python static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy

  # Prettier is a formatter for Mardown, YAML, JSON and others
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        args: ["--ignore-path", ".gitignore"]

  # TOML-sort sorts TOML files alphabetically
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args: ["--all", "--in-place"]
